#!/bin/bash

# ==============================================================================
# AUTOMATED DNSFILTER RELAY SETUP SCRIPT
# Tested on: Ubuntu 22.04 LTS
# ==============================================================================

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root (sudo ./setup_relay.sh)"
  exit
fi

clear
echo "========================================================"
echo "   DNSFilter Relay - Post-Install Automation"
echo "========================================================"

# --- PHASE 1: INPUT COLLECTION ---
echo ""
echo "--- 1. Configuration Inputs ---"

# Hostname
read -p "Enter desired Hostname (e.g., dns-relay): " NEW_HOSTNAME

# Credentials Setup (Optional)
echo ""
echo "If you need to reset the root password, enter it below. Leave blank to skip."
read -s -p "New Root Password (leave blank to skip): " ROOT_PASS
echo ""

# Network Configuration
echo ""
echo "--- Network Configuration ---"
# Detect interface
DETECTED_IFACE=$(ip -o -4 route show to default | awk '{print $5}' | head -n1)
read -p "Interface Name [default: $DETECTED_IFACE]: " IFACE_NAME
IFACE_NAME=${IFACE_NAME:-$DETECTED_IFACE}

read -p "Static IP with CIDR (e.g., 192.168.200.5/24): " STATIC_IP
read -p "Gateway IP (e.g., 192.168.200.1): " GATEWAY_IP
read -p "Primary DNS for OS (DNSFilter Primary): " DNS_PRI
read -p "Secondary DNS for OS (Google): " DNS_SEC
read -p "Search Domain (e.g., curvelake.ca): " SEARCH_DOMAIN

# DNSFilter Config
echo ""
echo "--- DNSFilter Relay Configuration ---"
read -p "Site/Network Name (e.g., Your Network): " RELAY_NAME
read -p "Secret Key: " RELAY_SECRET
read -p "Local DNS Server IP (Internal Windows DNS): " LOCAL_DNS_IP
read -p "Local Domains (comma separated, e.g., \"corp.loc\", \"files.loc\"): " LOCAL_DOMAINS
# Determine Jumpbox IP for SSH
read -p "Jumpbox/Management IP for SSH Access (e.g., 10.0.0.50): " JUMPBOX_IP

echo ""
echo "========================================================"
echo "Installing... Do not close this session."
echo "========================================================"

# --- PHASE 2: SYSTEM PREP ---

# Set Hostname
hostnamectl set-hostname "$NEW_HOSTNAME"
echo "Hostname set to $NEW_HOSTNAME"

# Update System
echo "Updating repositories and upgrading packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update && apt-get upgrade -y
apt-get install -y cron wget nano unzip unattended-upgrades

# --- PHASE 3: RESOLVED CONFIGURATION ---

echo "Configuring systemd-resolved to free up port 53..."
# Disable Stub Listener
sed -i 's/#DNSStubListener=yes/DNSStubListener=no/' /etc/systemd/resolved.conf
sed -i "s/#DNS=/DNS=$DNS_PRI $DNS_SEC/" /etc/systemd/resolved.conf

# Create symlink
ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf

# Restart resolved
systemctl restart systemd-resolved
echo "Systemd-resolved configured."

# --- PHASE 4: DNSFILTER RELAY INSTALLATION ---

echo "Downloading and installing Relay binary..."
mkdir -p /bin/relay
cd /bin/relay

wget -q https://download.dnsfilter.com/Relay/relay-linux-amd64
# Note: We generate our own config below, but downloading reference just in case
wget -q https://download.dnsfilter.com/Relay/relay.conf

chmod +x relay-linux-amd64

# --- PHASE 5: RELAY CONFIGURATION ---

echo "Generating relay.conf..."
cat > /bin/relay/relay.conf <<EOF
# Generated by Automation Script
[client]
  name = "$RELAY_NAME"
  secret_key = "$RELAY_SECRET"

[[local_dns_server]]
  addresses = [ "$LOCAL_DNS_IP:53" ]
  local_domains = [ $LOCAL_DOMAINS ]

# Networking
so_reuse_port = true
upstream_order = [ "udp", "tcp", "tcp-tls" ]

[log]
  level = "error"
EOF

# --- PHASE 6: SERVICE CREATION ---

echo "Creating Systemd Service..."
cat > /lib/systemd/system/relay.service <<EOF
[Unit]
Description=DNSFilter Relay Service
After=network.target

[Service]
Type=simple
ExecStart=/bin/relay/relay-linux-amd64
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable relay.service
systemctl start relay.service
echo "Relay service started."

# --- PHASE 7: SECURITY & MAINTENANCE ---

echo "Configuring Firewall (UFW)..."
ufw allow 53/tcp
ufw allow 53/udp
if [ ! -z "$JUMPBOX_IP" ]; then
    ufw allow from "$JUMPBOX_IP" to any port 22
else
    echo "Warning: No Jumpbox IP provided. Allowing SSH from ANYWHERE."
    ufw allow 22
fi
echo "y" | ufw enable

echo "Configuring Unattended Upgrades..."
cat > /etc/apt/apt.conf.d/20auto-upgrades <<EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF

# Append force options to 50unattended-upgrades
cat >> /etc/apt/apt.conf.d/50unattended-upgrades <<EOF
// Keep existing config during upgrades
Dpkg::Options {
   "--force-confdef";
   "--force-confold";
}
EOF

# --- PHASE 8: NETWORK CHANGES (LAST STEP) ---

# Handle Root Password Reset if requested
if [ ! -z "$ROOT_PASS" ]; then
    echo "root:$ROOT_PASS" | chpasswd
    echo "Root password updated."
fi

echo "Setting up Netplan and Cloud-Init overrides..."

# Disable Cloud Init Network Config
mkdir -p /etc/cloud/cloud.cfg.d
echo "network: {config: disabled}" > /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg

# Wipe existing netplan
rm -rf /etc/netplan/*

# Write new Netplan
# NOTE: Indentation is critical here.
cat > /etc/netplan/01-wired-interface-1.yaml <<EOF
network:
    ethernets:
        $IFACE_NAME:
            dhcp4: no
            dhcp6: no
            addresses:
            - $STATIC_IP
            nameservers:
                addresses:
                - $DNS_PRI
                - $DNS_SEC
                search:
                - $SEARCH_DOMAIN
            routes:
            -   to: default
                via: $GATEWAY_IP
    version: 2
EOF

chmod 600 /etc/netplan/01-wired-interface-1.yaml

echo "========================================================"
echo "SETUP COMPLETE."
echo "========================================================"
echo "The system will now apply network changes."
echo "WARNING: YOUR SSH CONNECTION WILL LIKELY DROP as the IP changes."
echo "Please reconnect using the new IP: $STATIC_IP"
echo ""
echo "Applying network changes now..."

# Apply Cloud-init clear and Netplan
cloud-init clear -r
netplan generate
netplan apply
